name: SSH into GCP VM

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build the Application using Ant Build
        run: |
          ROOT_PATH=$PWD
          echo $ROOT_PATH
          whoami
          hostname
          pwd
          ls -ltr

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 34.100.171.247
          username: deepankumarpandurangan
          key_path: ./private_key.ppk
          port: 22
          script: |
            hostname
            # Add your desired commands here
