name: SSH into GCP VM

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 34.100.171.247
          username: deepankumarpandurangan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Hello, GCP VM!"
            # Add your desired commands here
