name: SSH into GCP VM

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 34.100.171.247
          username: deepankumarpandurangan
          key: |
              -----BEGIN RSA PRIVATE KEY-----
              MIIJKAIBAAKCAgEA5u/8rLqA1lemZyf0Z03dEPJGNvmEgt5m4FJIzx4H+PGTG71X
              5zpMS3KUxFX/Hu7UVUrdiBY3CPEwbN5L3B0tTwevMIECNpLIuGWxOxy1+2hkWF5c
              POLUloOWuvYvEZzHJ0qm7IVW2Lvuvuw+WG2UsCWgUUkzVVFd1+shsBPv14xI2pnY
              wiEkwEZ/3QGVGnFNvELIvoHdC9bwUDFDEFfeIO0wFBLGLLB4KVXU9aSzQ7LNfpz0
              JPUxz4wNP11Z2w6M7YrSUpOq5n+9TS0G000eyiOd30zEBcRZsi9IN2V4kLu7dOBt
              6oSUyzIuqSShjY0x4K0llgA3r49IOOtyXV1Hf6NQZDM8NczQ9mPMVQ081ejzxOGI
              oSpoMQWryZc8tMtflO5j/4VSuYN7mAjG5pO81JYm1vB0QDmGKjoVQ9jtMJcmOQh/
              UWl+j1BANeUHnsqCn9s6jhTb0/3/kUHuSoAcWCKkF+csOr9fh2CopwNE9A1z0env
              jNnrxWdRtdtZtlPzbRG4ejT285pe+olsvbkrBXmXKX1So22CD3WJBPymlFBYw0aG
              Ws90Zpc+YzdrP3SZMKhYnPaArshWG5BfhrAlDHniqj+HFC6OQF3S5e2OBD8t4JQW
              T8ozAI9Dc63Vi565rZKy3Rwmk3YRqTcexLJdA3/af43yaXnunSjOqf59MocCAwEA
              AQKCAgEAovBwtu5gONte7Smjp7+oWmyWXfNvK2b/7wYfmQL3XQ4VXV0ayGq5qgIO
              NPj4KDsaVZOc+oeyDP0fzbCKlaOAdGJXmUFs7lRiirg1dB+txtTA+Bibu9nPZOMz
              VnacfzC+01o4rGjn/cObj9nfo0StxBrIIpIjRe9C5zVfb3yhnNO+E365ET+RTphv
              Xt/e8+k9j7cPLFs0O0ZMCEi5qK5Wa6TuZztX1/Aq1/9XYnnygbGGi+7x06Gso2ON
              dUfIPmblyDRKcTj/O+KlDe7XAf9H2heHLCZdqDQBlVcG/Q77IiNTAAPZib5BvZyK
              j4zo75bPulZwToWYxKWzr3VwG6/U4UJA6m7U3Q7g3XUgckEJj4KipnDntXv0x1yA
              IramTkseWJunJ1jRyo45bUIwp7RjifBso3PHWyXxxut5JEmFVzqwXj1Wb52hhJtL
              gnLN0N7dQwsrV1b0LqH2vF5OLNhl0HCJqhIG9NlJYpKeghP6Nb/faHMPbMG8PG3V
              akVuJ/pKR31nibfn+u1UcFORPSkaPsI4JoxIVg93l95aZ7uHyRRNxPvzQjpHN6hV
              Tq9ZC2VIdKbmk64AxFpPvdrOafoAQh50rxXDRx39Ci/qpbnpM7T/DFhkHkDlc7Qp
              oGyO7uP4+QiCywAkiFNOzlnYKGLzJjuFjKNMLGEai9jGm88avgECggEBAP6G+Iy5
              LTKNTMciATM1X/FONCllxWlr/YpMQg1c1hmIBako7DEQlBXltaDpjq3Hw9XsaTJv
              6YIjqEfoDKmBsEejCx6uzP9cNbSwK6e3r5CXd7GdLqK0kVeu/btDq6Qy4/2UZij2
              GrIfujfT9oGwjYzgnXVUlrWHsARPp8CSMcja72wHsq6dd4dZVPNAu1x4InywFGsO
              dPscP946A01NO/4qjg9PwJNoly9TlxPiQdkRwtmeqppOotWGSFB57lntln7Romis
              5p+qaD2F/LTEnJesR2L2ST4i8TXIi3xi1IT7cUnda6Gp0KaW74/AyLT8RMO9GnLe
              pGOlRQ3CsLob+S8CggEBAOhGEqCrXGE6vHJVx7Uz1ka85ojuvLrnocIyW3nhQoSY
              eBho8asbJthkeyTooIHMU8j2HGwbpD1s45Ps/tUw2zHiWtY2UGUUKiVOUz1mPJN8
              ELr8UW/2r9Yecs/GukhoyOHFq5Dw0QkvK8lVjJ3yPiRVVD4Vjx2b5mIF/xMGsMmI
              cp7gCtmEm6seo8VJ22rrW6e83nsQb92BaFxjs29OsJHVIdnkO2CqoDHPkGjDTmcn
              +MuQV/ADWe1ivIOupe6FFF8Jg8uW35l/K6zaKr8rp564sEU7AY8N0ejRx6ZKWOwr
              NQM7YYR/5yyJ87cZO55EK8ko3YcCUjZQiT/4ueZb1ikCggEAFqtUxcvUX7VAClhX
              /QSa9/X8JVfAHmSU31VtaJ1FIF8CCg/wAWq1lcGwzJUgtQ+evJXixLA8/u9IFKdx
              QUOgvLCj0+bDsVa4HdC3AqgUhe9HpNUYCzvD2ihmxt//EI/LyJEIDEvnEshKoKBL
              Sz+7S7nRrFqNVbuxDKE/kqIytu3w9xE0c+Loe3CUZVn1lgXJJIvWNbbC6n6YnaVT
              F/ZyCnAl2O1EfJyLIpbyVL4JGVlAnntIPJgWXqgoFqrVdML5bXAkY+hKXhwiTqB5
              YmxEeinI7eJ7oYIhM6YZ7kkrHnD6pRaIeIyUXdIBoi8McToqsbhM+8AiqhFVNiWJ
              8fl91wKCAQBqI/tHKIdidvC+XqyQBUwZryC52j6sOkUU9OYQX/uBlBrtLKeixRmP
              MPuE9jjCl5iB8NU0Ib1/xE6KvnYE/fpsZT+VO+SpC/nmalBnclykGMGccMjWHShk
              9C0K/YkKpbeGVEn+Rc2AIOolas6DLrtu5v9ED54CrcctbAgPrbMDpTKbn03V8F8i
              ZzH3abS2uy57DDeujOhRlF0YOwc4CgFt4rNBWqY3mkDyAiO/e+BMC1wJycAlkaJ6
              c/ApTJnO0Ulp1HNBiYRMJGzU5C08hrpmMYd7W2du86XEenh9aOQRp/zlqTD612fQ
              VonkVceEnypTFjWFCG6BG3Rco1BwD+9hAoIBAFAyNQkZxEdv4wqVN+E6olLxE/HG
              GjPsxWeborgsVJpsk2Pw27L8wMLv4gWfOFQTEY8t9uUfbMpgS4JIMxA1RolKhr/Z
              Vz7DM0fuwhTnI9bPjGB4l4zrDVRPOoSh3Z4a7O23IR0H/I3IubtBlP1ZHhnY45uw
              JHGDrwYnq4mX/EYCNAzbg5ve0OQq+zAiYY2AdYlke3CH6AHl4lJKK8J6wbKUUuLg
              ncp/CJA1cjpC/gLjVjQUn7LdDgQI3F0j8+DJ6BJ6FIyqgloVIs/XNFfm2Rq/pTbU
              v8XFL8+P4kWTOkhNyRzm8CDqcVwYxOf0LY07iNV/Yo6Ym5DVvLDr2Yn+hrM=
              -----END RSA PRIVATE KEY-----
          port: 22
          script: |
            echo "Hello, GCP VM!"
            # Add your desired commands here
