name: SSH into GCP VM

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build the Application using Ant Build
        run: |
          ROOT_PATH=$PWD
          echo $ROOT_PATH
          whoami
          hostname
          pwd
          ls -ltr
          ping -c 3 20.198.115.116
          
      - name: 🔎 Check IP
        run: curl https://api.ipify.org

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 20.198.115.116
          username: github_ssh_test_user
          key_path: ./github-ssh-test_key_ppk.ppk
          port: 22
          script: |
            hostname
            # Add your desired commands here
