name: SSH into GCP VM

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build the Application using Ant Build
        run: |
          ROOT_PATH=$PWD
          echo $ROOT_PATH
          whoami
          hostname
          pwd
          ls -ltr
#          ping -c 3 20.198.115.116
          
#      - name: 🔎 Check IP
#        run: curl https://api.ipify.org

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 4.224.33.11
          username: arvind
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./pom.xml
          target: "/home/arvind/"
          script: |
            ROOT_PATH=$PWD
            echo $ROOT_PATH
            whoami
            hostname
            pwd
            ls -ltr
            mkdir test_user
            ls -ltr
            
            # Add your desired commands here
