# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Maven Release

on:
    push:
        branches: [ main ]
jobs:
    build:
        name : Create Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Extract release notes
            id: extract-release-notes
            uses: ffurrer2/extract-release-notes@v1
          - name: Create release
            uses: actions/create-release@v1
            env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
