# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Maven Release

on: 
  milestone:
    types: [closed]
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Create Release Notes
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: oss@decathlon.com
        ACTION_NAME: decathlonbot
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: temp_release_notes
        OWNER: decathlon
        REPO_NAME: pull-request-labeler-action
        SKIP_MD: README.md
