name: Checkmarx SAST Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@<version>
      with:
        cxServer: https://github.com/depsai/java_Bootcamp.git
        cxUsername: depsai
        cxPassword: ${{ secrets.CX_PASSWORD }}
