name: Changelog Generator
on:
  push:
   branches:
     - main

jobs:
  generate:
      name: Changelog Generator
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
               fetch-depth: 0
